### ISSUE TITLE
Allow logging to file without syslog

### ISSUE THREAD

**Issue by ckristo** [jcbf/smf-spf#69]
Hi,

For a minimized docker image, it would be great if smf-spf can be configured to log to a file (e.g. /dev/stdout) instead of relying on syslog. What do you think?

Best regards,
Chris

**Comment by ckristo** [comment]
As additional input for the discussion, here the approaches of other mail-related Software:
  * postfix: allows to write log output to a file without the need of syslog via `maillog_file`, cf. http://www.postfix.com/MAILLOG_README.html
  * opendkim: requires syslog

**Comment by jcbf** [comment]
I'll take a look.

**Comment by jcbf** [comment]
@ckristo this works for you?
