### ISSUE TITLE
Compile failure on Debian 

### ISSUE THREAD

**Issue by tmaff** [jcbf/smf-spf#91]
I would like to use the tool on Debian. When compiling I always get "

~/smf-spf# make
gcc -O2 -D_REENTRANT -fomit-frame-pointer -I/usr/local/include  -c smf-spf.c
smf-spf.c:22:10: fatal error: arpa/inet.h: No such file or directory
 #include <arpa/inet.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:31: smf-spf.o] Error 1

". Do you have an idea why? :S

**Comment by jcbf** [comment]
Probably you need to install libc6-dev.
I usually do a 
 `apt-get -y install --no-install-recommends locales build-essential libmilter-dev libspf2-dev opendkim-tools lcov`
on ubuntu . For Debian should be similar.

opendkim-tools and lcov is used for testing only
